Query:
  type: object
  config:
    fields:
      author:
        type: User
        args:
          id:
            type: Int
        resolve: '@=resolver("App\\GraphQL\\Resolver\\UserResolver::resolve", [args["id"]])'